### ISSUE TITLE
adapter currently only supports buzz 0.15.*, not 0.16 or 0.17

### ISSUE THREAD

**Issue by tolry** [php-http/buzz-adapter#19]
| Q            | A
| ------------ | ---
| Bug?         | ?
| New Feature? | no
| Version      | master

#### Actual Behavior

https://github.com/php-http/buzz-adapter/blob/6f734e55d58256c33ef601788a23db87629b8ee0/composer.json#L16

buzz composer constraint was changed from `^0.15` to `^0.15.1`, resulting in making it not usable with `0.16` `0.17` (current stable) - was this intentional?

#### Expected Behavior

`composer require kriswallsmith/buzz php-http/buzz-adapter` should work, currently resulting in

![buzz-require-conflict](https://user-images.githubusercontent.com/259744/46680540-999fb800-cbe9-11e8-9f75-f41464b8b2a0.png)

#### Steps to Reproduce

see composer command above

#### Possible Solutions

If the adapter is still compatible with 0.16/17, just open up composer constraints.

Thanks!

**Comment by tolry** [comment]
to give a bit more context on this

* `0.*` is differently handled in composer than everything `>=1.0` with caret version range, see https://getcomposer.org/doc/articles/versions.md#caret-version-range-
* my actual case is: I have a project using buzz `0.16` and needed a PSR compliant HTTP client for another library and wanted to re-use buzz for that

**Comment by dbu** [comment]
can you send a pull request that allows those versions and we see if it builds?

@Nyholm are you aware of breaking changes in buzz? is there a reason there is no 1.0 of buzz yet?

**Comment by tolry** [comment]
sure, see #20

**Comment by Nyholm** [comment]
>  are you aware of breaking changes in buzz?

Yes. I made them =)

>  is there a reason there is no 1.0 of buzz yet?

We are just waiting on PSR18 (my bad). 

Buzz should release a RC1.

**Comment by tolry** [comment]
closing here, since incompatibility is intentional - newer versions of buzz don't need this adapter anymore
