### ISSUE TITLE
Tag version 0.2.1 ?

### ISSUE THREAD

**Issue by Nyholm** [php-http/buzz-adapter#6]
Reviewing the work of @lboynton and the few other commits I see that we keep BC. We should update our patch version (since this is <1.0.0).

**Comment by sagikazarmark** [comment]
What keeps us from releasing a stable version?

**Comment by Nyholm** [comment]
php-http/discovery 

Just like guzzle5

**Comment by sagikazarmark** [comment]
Can we tag a stable then? After #8

**Comment by Nyholm** [comment]
Lets wait for a while. The life of this adapter has been very short. Lets tag 0.3.0 after #8 and hope that 1.0 = 0.3 after a couple of months.
